config/routes.rb
KingsCup::Application.routes.draw do
  root to: 'games#index'
  resources :games, except: [:edit, :update, :destroy]
  resources :players, only: [:index, :new, :create]
end

app/models/card.rb
class Card < ActiveRecord::Base
  def self.mission_for(card)
    key_name = card.name.split(' ')[0].downcase
    message = I18n.t("cards.card_#{key_name}")

    "#{key_name.upcase}: #{message}"
  end
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :game_players
  has_many :players, through: :game_players

  has_many :player_game_cards
  has_many :cards, through: :player_game_cards

  accepts_nested_attributes_for :game_players
end

app/models/game_player.rb
class GamePlayer < ActiveRecord::Base
  belongs_to :game
  belongs_to :player
end

app/models/player.rb
class Player < ActiveRecord::Base
end

app/models/player_game_card.rb
class PlayerGameCard < ActiveRecord::Base
  belongs_to :player
  belongs_to :game
  belongs_to :card
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
  end

  def new
    @game = Game.new
    @game.game_players.build
  end

  def create
    @game = Game.new(games_params)

    @game.save
    redirect_to @game
  end

  def show
    @game = Game.find(params[:id])
    players = @game.players
    last_player_game_card = @game.player_game_cards.last

    last_player = if last_player_game_card
      last_player_game_card.player
    else
      players.first
    end

    current_player_index = players.index(last_player) + 1

    if players.length == current_player_index
      current_player_index = 0
    end

    all_cards = Card.all.to_a
    used_cards = @game.cards.to_a
    remaining_cards = all_cards - used_cards
    @selected_card = remaining_cards.sample

    king_cards = remaining_cards.select do |card|
      card.name.include?('King')
    end
    @current_player = players.at(current_player_index)

    if king_cards.length == 1 && @selected_card == king_cards.first
      render :loser and return
    end

    PlayerGameCard.create(game: @game,
      player: @current_player,
      card: @selected_card
    )
  end

  private

  def games_params
    params.require(:game).permit(game_players_attributes: [:player_id])
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
  end

  def new
    @player = Player.new
  end

  def create
    @player = Player.new(player_params)
    @player.save
    redirect_to players_path
  end

  private

  def player_params
    params.require(:player).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/games/index.html.erb
<%= link_to 'Start a new game', new_game_path %>

app/views/games/loser.html.erb
<h1>HAHAHAHAHAHA</h1>
<h2>DRINK, <%= @current_player.name.upcase + ("!" * 50) %>, YOU PICKED THE <%= @selected_card.name.upcase %></h2>

<hr>
<%= link_to "New game", new_game_path %>

app/views/games/new.html.erb
<%= simple_form_for @game do |form| %>
  <div id="container">
    <%= form.simple_fields_for :game_players do |ff| %>
      <div>
        <%= ff.association :player %>
        <a href="#" class="destroy">×</a>
      </div>
    <% end %>
  </div>

  <a href="#" id="add_another">+ add another</a>
  <hr />
  <%= form.submit %>
<% end %>

<script type="text/javascript">
  $("#container").nestedAttributes({
    bindAddTo: $("#add_another")
  });
</script>

app/views/games/show.html.erb
<%= @current_player.name %>
<hr>
Your card: <%= @selected_card.name %>
<hr>
Your mission, <small>should you choose to accept it (<span style="font-size: 4px">Which you have too</span>)</small>
<hr>
<%= Card.mission_for(@selected_card) %>

<hr>

<%= link_to 'Next Player' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KingsCup</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/players/index.html.erb
<%= link_to 'Add a player', new_player_path %>

app/views/players/new.html.erb
<%= simple_form_for @player do |form| %>
  <%= form.input :name %>
  <%= form.submit %>
<% end %>